/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "secondary-container": "#fe7488",
              "surface-container-high": "#dce9ff",
              "surface": "#f8f9ff",
              "background": "#f8f9ff",
              "tertiary-fixed": "#dae2fd",
              "surface-variant": "#d3e4fe",
              "secondary-fixed-dim": "#ffb2b9",
              "primary-fixed-dim": "#6bd8cb",
              "on-secondary-fixed": "#400010",
              "on-primary-container": "#f4fffc",
              "inverse-surface": "#213145",
              "surface-dim": "#cbdbf5",
              "on-secondary-container": "#730425",
              "on-secondary-fixed-variant": "#891933",
              "primary-container": "#008378",
              "on-error": "#ffffff",
              "on-tertiary-container": "#fefcff",
              "on-secondary": "#ffffff",
              "error": "#ba1a1a",
              "on-tertiary": "#ffffff",
              "outline": "#6d7a77",
              "on-background": "#0b1c30",
              "surface-container": "#e5eeff",
              "outline-variant": "#bcc9c6",
              "tertiary-fixed-dim": "#bec6e0",
              "on-primary": "#ffffff",
              "error-container": "#ffdad6",
              "surface-bright": "#f8f9ff",
              "on-tertiary-fixed-variant": "#3f465c",
              "primary": "#00685f",
              "on-error-container": "#93000a",
              "surface-container-highest": "#d3e4fe",
              "on-tertiary-fixed": "#131b2e",
              "on-surface": "#0b1c30",
              "inverse-primary": "#6bd8cb",
              "on-surface-variant": "#3d4947",
              "secondary-fixed": "#ffdadc",
              "tertiary": "#545c72",
              "on-primary-fixed-variant": "#005049",
              "inverse-on-surface": "#eaf1ff",
              "surface-tint": "#006a61",
              "on-primary-fixed": "#00201d",
              "secondary": "#a93349",
              "tertiary-container": "#6c748b",
              "primary-fixed": "#89f5e7",
              "surface-container-lowest": "#ffffff",
              "surface-container-low": "#eff4ff"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "md": "16px",
              "xs": "4px",
              "gutter": "24px",
              "margin-desktop": "48px",
              "margin-mobile": "16px",
              "sm": "8px",
              "xl": "40px",
              "xxl": "64px",
              "lg": "24px",
              "base": "4px"
          },
          "fontFamily": {
              "label-md": ["Inter", "sans-serif"],
              "body-sm": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "display-lg": ["Inter", "sans-serif"],
              "headline-lg-mobile": ["Inter", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "title-lg": ["Inter", "sans-serif"],
              "headline-md": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"]
          },
          "fontSize": {
              "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
              "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
              "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
              "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
              "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
              "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
              "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
          }
      }
  },
  plugins: [],
}
